name: Bug Report
description: Report a bug or issue with the repository
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please provide as much detail as possible.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Undertow Sample
        - Spring Boot Sample
        - Tomcat Sample
        - WildFly Sample
        - Build Scripts
        - Validation Scripts
        - OpenShift BuildConfig
        - Kubernetes Manifests
        - Documentation
        - Other
    validations:
      required: true

  - type: input
    id: java-version
    attributes:
      label: Java Version
      description: Which Java version are you using?
      placeholder: "e.g., OpenJDK 17"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: Describe the issue...
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Run command '...'
        2. Observe error '...'
        3. Expected behavior '...'
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Paste any relevant error logs
      render: shell
      placeholder: |
        # Paste logs here
        
    validations:
      required: false

  - type: dropdown
    id: environment
    attributes:
      label: Environment
      description: Where are you running this?
      options:
        - OpenShift 4.x
        - Kubernetes
        - Local (Podman)
        - Local (Docker)
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Repository Version
      description: Which version/commit of the repository?
      placeholder: "e.g., main branch, v2.0.0, commit hash"
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the problem
    validations:
      required: false

  - type: checkboxes
    id: validation
    attributes:
      label: Validation Steps Taken
      description: Have you run the validation scripts?
      options:
        - label: I have run `./scripts/validate-all-builds.sh`
        - label: I have checked the documentation in TESTING.md
        - label: I have reviewed TROUBLESHOOTING section in TESTING.md
        - label: This is a new issue not previously reported
