FROM registry.access.redhat.com/ubi8/openjdk-11:1.21 AS builder
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

FROM registry.access.redhat.com/ubi8/openjdk-11-runtime:1.21
COPY --from=builder /app/target/metrics-sample-springboot-1.0.0.jar /app/app.jar
EXPOSE 8080
ENV JAVA_OPTS="-Xlog:os+container=info -XX:MaxRAMPercentage=70.0 -XX:InitialRAMPercentage=50.0"
ENV TOMCAT_MAX_THREADS=50
CMD java $JAVA_OPTS -jar /app/app.jar
